### ISSUE TITLE
Set to push on "master", but pushing on "main"

### ISSUE THREAD

**Issue by AlexMorgan3817** [actions/.github#22]
![image](https://user-images.githubusercontent.com/46600554/103458762-bb8f3300-4d3d-11eb-8c11-0cfb8a366a9b.png)
Workflow is set to push on "master", but it's trying to push on "main"
![image](https://user-images.githubusercontent.com/46600554/103458778-e7aab400-4d3d-11eb-9f0d-0b986b0d418a.png)

**Comment by affrae** [comment]
Hi @AlexMorgan3817 this is not quite the right place to open issues with third party actions, however I will try and assist here.

That workflow is set to use the version of `ad-m/github-push-action` that is currently at the HEAD of `master`. That is what `ad-m/github-push-action@master` means

You need to provide the actual branch you want to push to as a parameter, for example:

``` yml
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
```
I went and checked the action and by default if you do not provide a `branch:` parameter, it will default to trying to push to `main`.

If you have any further issues with that action it is a better option to go and check with the author. Hope this helps...
